-- Drop tables safely (re-runnable)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ME_ROOM_CALENDAR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ME_VOLUNTEERS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ME_ROOM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Tables
CREATE TABLE ME_ROOM (
    NAME_ROOM     VARCHAR2(100),
    PLACE         VARCHAR2(100),
    NUMBER_BEDS   NUMBER
);

CREATE TABLE ME_VOLUNTEERS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME            VARCHAR2(100),
    STATUS          VARCHAR2(20),
    ARRIVAL_DATE    DATE,
    DEPARTURE_DATE  DATE,
    PLACE           VARCHAR2(100)
);

CREATE TABLE ME_ROOM_CALENDAR (
    ROOM_NAME                  VARCHAR2(100),
    PLACE                      VARCHAR2(100),
    ARRIVAL_DATE               DATE,
    DEPARTURE_DATE             DATE,
    BOOKED__FOR__VOLUNTEER     VARCHAR2(100)
);