-- Sample Rooms
INSERT INTO ME_ROOM VALUES ('Room A', 'Berlin', 2);
INSERT INTO ME_ROOM VALUES ('Room B', 'Berlin', 3);
INSERT INTO ME_ROOM VALUES ('Room C', 'Berlin', 2);

-- Sample Volunteers
INSERT INTO ME_VOLUNTEERS (NAME, STATUS, ARRIVAL_DATE, DEPARTURE_DATE, PLACE)
VALUES ('Alice', 'Confirmed', DATE '2026-01-01', DATE '2026-01-10', 'Berlin');

INSERT INTO ME_VOLUNTEERS (NAME, STATUS, ARRIVAL_DATE, DEPARTURE_DATE, PLACE)
VALUES ('Bob', 'Confirmed', DATE '2026-01-01', DATE '2026-01-05', 'Berlin');

INSERT INTO ME_VOLUNTEERS (NAME, STATUS, ARRIVAL_DATE, DEPARTURE_DATE, PLACE)
VALUES ('Charlie', 'Confirmed', DATE '2026-01-06', DATE '2026-01-10', 'Berlin');

-- Room Calendar
INSERT INTO ME_ROOM_CALENDAR VALUES ('Room B','Berlin',DATE '2026-01-01',DATE '2026-01-10','Alice');
INSERT INTO ME_ROOM_CALENDAR VALUES ('Room B','Berlin',DATE '2026-01-01',DATE '2026-01-05','Bob');
INSERT INTO ME_ROOM_CALENDAR VALUES ('Room B','Berlin',DATE '2026-01-06',DATE '2026-01-10','Charlie');

COMMIT;