-- Daily Expansion (Accurate but heavier)

WITH DRIVER AS (
  SELECT :P_ARRIVAL + LEVEL - 1 DT
  FROM DUAL
  CONNECT BY LEVEL <= :P_DEPARTURE - :P_ARRIVAL + 1
),
ROOM_BED_OCCUPANCY_EACH_DAY AS (
  SELECT RC.ROOM_NAME,
         COUNT(*) BEDS_OCCUPIED
  FROM ME_ROOM_CALENDAR RC
  JOIN ME_VOLUNTEERS V
    ON RC.BOOKED__FOR__VOLUNTEER = V.NAME
  JOIN DRIVER D
    ON D.DT BETWEEN RC.ARRIVAL_DATE AND RC.DEPARTURE_DATE
  WHERE RC.PLACE = :P_PLACE
  AND V.STATUS = 'Confirmed'
  GROUP BY RC.ROOM_NAME, D.DT
),
ROOM_MAX AS (
  SELECT ROOM_NAME,
         MAX(BEDS_OCCUPIED) MAX_OCCUPIED
  FROM ROOM_BED_OCCUPANCY_EACH_DAY
  GROUP BY ROOM_NAME
)
SELECT R.NAME_ROOM,
       R.NUMBER_BEDS - NVL(M.MAX_OCCUPIED,0) BEDS_REMAINING
FROM ME_ROOM R
LEFT JOIN ROOM_MAX M
  ON R.NAME_ROOM = M.ROOM_NAME
WHERE R.PLACE = :P_PLACE
ORDER BY R.NAME_ROOM;