-- Improved Schema (Explicit Beds)

BEGIN EXECUTE IMMEDIATE 'DROP TABLE BED_BOOKING'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BED'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROOM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE ROOM (
    ROOM_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    ROOM_NAME   VARCHAR2(100),
    PLACE       VARCHAR2(100),
     CONSTRAINT ROOM_PK PRIMARY KEY (ROOM_ID)
);

CREATE TABLE BED (
    BED_ID      NUMBER GENERATED ALWAYS AS IDENTITY,
    ROOM_ID     NUMBER,
    BED_NUMBER  NUMBER,
     CONSTRAINT BED_PK PRIMARY KEY (BED_ID),
    CONSTRAINT fk_bed_room FOREIGN KEY (ROOM_ID)
        REFERENCES ROOM(ROOM_ID)
);

CREATE TABLE BED_BOOKING (
    BOOKING_ID      NUMBER GENERATED ALWAYS AS IDENTITY,
    BED_ID          NUMBER,
    VOLUNTEER_NAME  VARCHAR2(100),
    ARRIVAL_DATE    DATE,
    DEPARTURE_DATE  DATE,
    CONSTRAINT fk_booking_bed FOREIGN KEY (BED_ID)
        REFERENCES BED(BED_ID)
);